# application.conf is not loaded when using config.resource for cluster mode.
# This file is only used for single-node dev mode (mvn compile exec:java).
akka.javasdk {
  dev-mode {
    persistence.enabled = true
  }
}
